export const CATEGORIES_ACTION_TYPES =  {
  FETCH_CATEGORIES_START: '[CATEGORIES] FETCH CATEGORIES START',
  FETCH_CATEGORIES_SUCCESS: '[CATEGORIES] FETCH CATEGORIES SUCCESS',
  FETCH_CATEGORIES_FAILURE: '[CATEGORIES] FETCH CATEGORIES FAILED',
}
