export const CATEGORIES_ACTION_TYPES =  {
  FETCH_CATEGORIES_START: '[CATEGORIES] Fetch Categories Start',
  FETCH_CATEGORIES_SUCCESS: '[CATEGORIES] Fetch Categories Success',
  FETCH_CATEGORIES_FAILURE: '[CATEGORIES] Fetch Categories Failure',
}
