export const CART_ACTION_TYPES = {
  SET_CART_ITEMS: '[CART] SET CART ITEMS',
  SET_CART_OPEN: '[CART] SET CART OPEN',
  SET_CART_COUNT: '[CART] SET CART COUNT',
  SET_CART_TOTAL: '[CART] SET CART TOTAL'
}